// Generated by scripts/sync-practice-images.mjs — do not edit by hand
export const practiceImagesBySlug: Record<string, string[]> = {
  "golden-hour": [
    "/images/practice/golden-hour/01.jpg",
    "/images/practice/golden-hour/02.jpg",
    "/images/practice/golden-hour/03.jpg",
  ],
  "insistence-of-red": [
    "/images/practice/insistence-of-red/01.jpg",
    "/images/practice/insistence-of-red/02.jpg",
    "/images/practice/insistence-of-red/03.jpg",
  ],
};
