// Generated by scripts/sync-sketch-images.mjs — do not edit by hand
export const sketchImagesBySlug: Record<string, string[]> = {
  "age-30": [
    "/images/sketch/age-30/01.jpg",
    "/images/sketch/age-30/02.jpg",
    "/images/sketch/age-30/03.jpg",
  ],
  "baby-boy": [
    "/images/sketch/baby-boy/01.jpg",
    "/images/sketch/baby-boy/02.jpg",
    "/images/sketch/baby-boy/03.jpg",
  ],
  "banaras": [
    "/images/sketch/banaras/01.jpg",
    "/images/sketch/banaras/02.jpg",
    "/images/sketch/banaras/03.jpg",
  ],
  "boy": [
    "/images/sketch/boy/01.jpg",
  ],
  "fear": [
    "/images/sketch/fear/01.jpg",
  ],
  "hand-detailing": [
    "/images/sketch/hand-detailing/01.jpg",
  ],
  "happy-girl": [
    "/images/sketch/happy-girl/01.jpg",
  ],
  "old-man": [
    "/images/sketch/old-man/01.jpg",
  ],
  "opticals": [
    "/images/sketch/opticals/01.jpg",
    "/images/sketch/opticals/02.jpg",
  ],
  "society": [
    "/images/sketch/society/01.jpg",
    "/images/sketch/society/02.jpg",
    "/images/sketch/society/03.jpg",
    "/images/sketch/society/04.jpg",
  ],
};
