// Generated by scripts/sync-sketch-images.mjs — do not edit by hand
export const sketchesMeta: { slug: string; title: string }[] = [
  { slug: "society", title: "Society" },
  { slug: "old-man", title: "Old Man" },
  { slug: "boy", title: "Boy" },
  { slug: "hand-detailing", title: "Hand Detailing" },
  { slug: "happy-girl", title: "Happy Girl" },
  { slug: "fear", title: "Fear" },
  { slug: "opticals", title: "Opticals" },
  { slug: "age-30", title: "Age 30" },
  { slug: "banaras", title: "Banaras" },
  { slug: "baby-boy", title: "Baby Boy" },
];
