// Generated by scripts/sync-takhleeq-images.mjs — do not edit by hand
export const imagesByWorkNumber: Record<string, string[]> = {
  "01": [
    "/images/takhleeq/ganesha/01.jpg",
    "/images/takhleeq/ganesha/02.jpg",
    "/images/takhleeq/ganesha/03.jpg",
    "/images/takhleeq/ganesha/04.jpg",
  ],
  "02": [
    "/images/takhleeq/life-unexpected/01.jpg",
  ],
  "03": [
    "/images/takhleeq/nazariya/01.jpg",
    "/images/takhleeq/nazariya/02.jpg",
    "/images/takhleeq/nazariya/03.jpg",
    "/images/takhleeq/nazariya/04.jpg",
    "/images/takhleeq/nazariya/05.jpg",
  ],
  "04": [
    "/images/takhleeq/afsos/01.jpg",
    "/images/takhleeq/afsos/02.jpg",
    "/images/takhleeq/afsos/03.jpg",
    "/images/takhleeq/afsos/04.jpg",
    "/images/takhleeq/afsos/05.jpg",
  ],
  "05": [
    "/images/takhleeq/krupa/01.jpg",
    "/images/takhleeq/krupa/02.jpg",
    "/images/takhleeq/krupa/03.jpg",
    "/images/takhleeq/krupa/04.jpg",
  ],
  "06": [
    "/images/takhleeq/dard-se-takhleeq/01.jpg",
    "/images/takhleeq/dard-se-takhleeq/02.jpg",
    "/images/takhleeq/dard-se-takhleeq/03.jpg",
    "/images/takhleeq/dard-se-takhleeq/04.jpg",
    "/images/takhleeq/dard-se-takhleeq/05.jpg",
  ],
  "07": [
    "/images/takhleeq/bhatakta-hua/01.jpg",
    "/images/takhleeq/bhatakta-hua/02.jpg",
    "/images/takhleeq/bhatakta-hua/03.jpg",
    "/images/takhleeq/bhatakta-hua/04.jpg",
  ],
  "08": [
    "/images/takhleeq/ehsaas/01.jpg",
    "/images/takhleeq/ehsaas/02.jpg",
    "/images/takhleeq/ehsaas/03.jpg",
  ],
  "09": [
    "/images/takhleeq/gussa/01.jpg",
    "/images/takhleeq/gussa/02.jpg",
  ],
  "10": [
    "/images/takhleeq/bahuroopiya/01.jpg",
    "/images/takhleeq/bahuroopiya/02.jpg",
  ],
  "11": [
    "/images/takhleeq/aaraish-e-maazi/01.jpg",
    "/images/takhleeq/aaraish-e-maazi/02.jpg",
    "/images/takhleeq/aaraish-e-maazi/03.jpg",
    "/images/takhleeq/aaraish-e-maazi/04.jpg",
    "/images/takhleeq/aaraish-e-maazi/05.jpg",
    "/images/takhleeq/aaraish-e-maazi/06.jpg",
  ],
  "12": [
    "/images/takhleeq/splashing-mind/01.jpg",
    "/images/takhleeq/splashing-mind/02.jpg",
    "/images/takhleeq/splashing-mind/03.jpg",
    "/images/takhleeq/splashing-mind/04.jpg",
    "/images/takhleeq/splashing-mind/05.jpg",
    "/images/takhleeq/splashing-mind/06.jpg",
  ],
  "13": [
    "/images/takhleeq/love-letter/01.jpg",
    "/images/takhleeq/love-letter/02.jpg",
    "/images/takhleeq/love-letter/03.jpg",
  ],
  "14": [
    "/images/takhleeq/iztirab/01.jpg",
    "/images/takhleeq/iztirab/02.jpg",
    "/images/takhleeq/iztirab/03.jpg",
    "/images/takhleeq/iztirab/04.jpg",
    "/images/takhleeq/iztirab/05.jpg",
    "/images/takhleeq/iztirab/06.jpg",
    "/images/takhleeq/iztirab/07.jpg",
  ],
  "15": [
    "/images/takhleeq/haqeeqat/01.jpg",
    "/images/takhleeq/haqeeqat/02.jpg",
    "/images/takhleeq/haqeeqat/03.jpg",
  ],
  "16": [
    "/images/takhleeq/bantwara/01.jpg",
  ],
  "17": [
    "/images/takhleeq/aakhir-e-shab/01.jpg",
    "/images/takhleeq/aakhir-e-shab/02.jpg",
  ],
  "18": [
    "/images/takhleeq/kya-karein/01.jpg",
    "/images/takhleeq/kya-karein/02.jpg",
  ],
  "19": [
    "/images/takhleeq/taqdeer/01.jpg",
    "/images/takhleeq/taqdeer/02.jpg",
    "/images/takhleeq/taqdeer/03.jpg",
  ],
  "20": [
    "/images/takhleeq/alahda/01.jpg",
    "/images/takhleeq/alahda/02.jpg",
  ],
  "21": [
    "/images/takhleeq/find-your-way/01.jpg",
    "/images/takhleeq/find-your-way/02.jpg",
  ],
  "22": [
    "/images/takhleeq/finding-purpose/01.jpg",
    "/images/takhleeq/finding-purpose/02.jpg",
    "/images/takhleeq/finding-purpose/03.jpg",
    "/images/takhleeq/finding-purpose/04.jpg",
  ],
};
